services:
  backend:
    build:
      context: './backend'
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    container_name: 'exam-platform-backend'
    restart: 'always'
    ports:
      - '${HOST_MACHINE_BACKEND_PORT}:8000'
    links:
      - mysql
      - ollama
    environment:
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      LLM_BASE_URL: '${LLM_BASE_URL}'
  client:
    build:
      context: './client'
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: 'exam-platform-client'
    restart: 'always'
    ports:
      - '${HOST_MACHINE_CLIENT_PORT}:3000'
    environment:
      REACT_APP_API_URL: '${API_URL}'
  mysql:
    image: '${DB_SERVER}'
    container_name: 'exam-platform-db'
    restart: 'always'
    ports:
      - '${HOST_MACHINE_MYSQL_PORT}:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'exam-platform-phpmyadmin'
    restart: 'always'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${HOST_MACHINE_PHPMYADMIN_PORT}:80'
  ollama:
    image: ollama/ollama:latest
    container_name: 'exam-platform-ollama'
    restart: 'always'
    ports:
      - '${HOST_MACHINE_OLLAMA_PORT}:11434'
